module.exports = [
  {
    name: "default",
    type: "postgres",
    url: process.env.DATABASE_URL,
    synchronize: false,
    logging: false,
    entities: ["dist/entities/*.*"],
    migrations: ["dist/database/migrations/**/*.js"],
    subscribers: ["dist/database/subscribers/**/*.js"],
    cli: {
      entitiesDir: "dist/entities",
      migrationsDir: "dist/database/migrations",
      subscribersDir: "dist/database/subscribers",
    },
  },
  {
    name: "dockerized",
    type: "postgres",
    port: 5555,
    username: "postgres",
    password: "postgres",
    database: "lab",
    synchronize: true,
    logging: true,
    entities: ["src/entity/**/*.js"],
    migrations: ["src/migration/**/*.js"],
    subscribers: ["src/subscriber/**/*.js"],
    cli: {
      entitiesDir: "src/entity",
      migrationsDir: "src/migration",
      subscribersDir: "src/subscriber",
    },
  },
  {
    name: "development",
    type: "postgres",
    host: "localhost",
    port: 5432,
    username: "postgres",
    password: "postgres",
    database: "lab",
    synchronize: true,
    logging: true,
    entities: ["src/entity/**/*.ts"],
    migrations: ["src/migration/**/*.ts"],
    subscribers: ["src/subscriber/**/*.ts"],
    cli: {
      entitiesDir: "src/entity",
      migrationsDir: "src/migration",
      subscribersDir: "src/subscriber",
    },
  },
];
